remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: Hunter Wilson Data Analytics Portfolio
theme: jeykll-theme-tactile
description: A repository to showcase my various Python and R projects. 
